In [1]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura_em_metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [16]:
lista_de_centimetros = list(range(170, 190, 5))
lista_de_centimetros

[170, 175, 180, 185]

In [18]:
altura_em_centimetros = np.array(lista_de_centimetros)
altura_em_centimetros

array([170, 175, 180, 185])

In [20]:
altura_em_metros = altura_em_centimetros / 100.0

print("Alturas em centímetros:", altura_em_centimetros)
print("Alturas em metros:", altura_em_metros)

Alturas em centímetros: [170 175 180 185]
Alturas em metros: [1.7  1.75 1.8  1.85]


### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [39]:
lista_pesos = [70, 75, 80, 85]
lista_pesos
# seu código aqui
pesos = np.array(lista_pesos)
pesos
lista_altura = [1.70 , 1.80, 1.90, 1.65]
altura = np.array(lista_altura)
altura


array([1.7 , 1.8 , 1.9 , 1.65])

In [52]:
# calcule o IMC dessas pessoas
def calcula_IMC(peso,altura):
    imc = peso/(altura**2)
    return imc

In [53]:
imc2 = calcula_IMC(pesos,altura)
type(imc2)
print(imc2)

[24.22145329 23.14814815 22.16066482 31.22130395]


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [59]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
dados_financeiros
#i) transforme essa lista em um ndarray
nd_financeiro = np.array(dados_financeiros)
print(nd_financeiro)


[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [85]:
# ii) 
nd_financeiro = nd_financeiro.transpose() # transpõe o ndarray
print(nd_financeiro) # imprime o ndarray transposto

print('Segunda linha do array:',nd_financeiro[1]) # imprime a segunda linha do array
print('Segunda coluna do array:',nd_financeiro[:, 1]) # imprime a segunda coluna do array




[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500 10000 16000]]
Segunda linha do array: [1000 2500 3000 5000]
Segunda coluna do array: [2500 2500 5500]


In [86]:
# iii) 
# Calcule o endividamento total
endividamento_total = (nd_financeiro[:, 0] + nd_financeiro[:, 1]) / nd_financeiro[:, 2] # calcula o endividamento total
print(endividamento_total) # imprime o endividamento total



[5.5        1.16666667 1.15      ]


In [88]:
# iv) corrigindo um valor específico

nd_financeiro[2, 2] = 10000 # corrige o valor da renda familiar do terceiro indivíduo
print(nd_financeiro) # imprime o ndarray corrigido


endividamento_total = (nd_financeiro[:, 0] + nd_financeiro[:, 1]) / nd_financeiro[:, 2] # recalcula o endividamento total
print('Segue o endividamento total:', endividamento_total) # imprime o endividamento total corrigido



[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500 10000 16000]]
Segue o endividamento total: [5.5        1.16666667 1.15      ]


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [89]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [95]:
# i) Criar um objeto bool_zero com valores True quando poi é zero e False caso contrário

# Exemplo: gerando um array de números pseudoaleatórios
poi = np.random.rand(100)  
bool_zero = (poi == 0)


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [93]:
# ii) Conte a quantidade de zeros (ou some os elementos de bool_zero)

num_zeros = np.sum(bool_zero)


0

In [92]:
# iii) utilize a indexação booleana para criar uma seleção de não-zeros
# dica: inverta o objeto bool_zero

poi_nao_zero = poi[~bool_zero]

print("bool_zero:", bool_zero)
print("Número de valores zero:", num_zeros)
print("poi_nao_zero:", poi_nao_zero)

bool_zero: [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]
Número de valores zero: 0
poi_nao_zero: [0.8335869  0.36994852 0.936557   0.48305288 0.12533161 0.96445418
 0.01702583 0.67657077 0.14043997 0.15531285 0.64955775 0.98165422
 0.69480742 0.76197389 0.42520918 0.13889344 0.2161863  0.76470027
 0.05460587 0.49012299 0.18069018 0.63092485 0.55124203 0.56708121
 0.81834498 0.9389873  0.19290141 0.71284402 0.6979398  0.2582965
 0.91